___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1


#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

Вивести версію та конфігурацію бібліотеки:

In [3]:

import numpy as np


Z = np.ones(10)
Z

Створити вектор з 10 елементів, заповнений одиницями:

In [5]:
import numpy as np

Z = np.arange(0,11, 1)
Z

Створити вектор із значеннями від 0 до 10:

In [6]:
import numpy as np

Z = np.zeros((5,5))

Z

Створити матрицю 5 на 5, заповнену нулями:

In [37]:
import numpy as np

Z = np.random.randint(0,3,20)


print(Z)
np.nonzero(Z)

[0 1 1 0 1 1 0 2 1 0 0 0 1 0 2 0 0 2 2 0]


(array([ 1,  2,  4,  5,  7,  8, 12, 14, 17, 18]),)

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [41]:
import numpy as np

Z = np.random.randint(0,3,20)

mean = np.mean(Z)
std = np.std(Z)
median = np.median(Z)

print(mean)
print(std)
print(median)

1.1
0.7681145747868608
1.0


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [65]:
import numpy as np # Число колонок певрой матрицы должно быть равно числу строк второй

Z = np.random.randint(1,10,(4,2))
X = np.random.randint(1,10,(2,2))

Y = np.dot(Z,X)

Y

Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [22]:
import numpy as np # Число колонок певрой матрицы должно быть равно числу строк второй

Z = np.random.randint(1,10,(4,2))
X = np.random.randint(1,10,(2,2))

Y = np.dot(Z,X).reshape(8,1)
Y

min = np.min(Y)
max = np.max(Y)

indMax =  np.argmax(Y) # индекс максимального элемента
print(Y)
Y[indMax] = 0
print(Y)

[[66]
 [72]
 [45]
 [68]
 [51]
 [58]
 [39]
 [52]]
[[66]
 [ 0]
 [45]
 [68]
 [51]
 [58]
 [39]
 [52]]


Результу
ючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [64]:
Z = np.random.randint(1,10,(4,2))
X = np.random.randint(1,10,(2,2))

Y = np.dot(Z,X)




my_rho1 = np.corrcoef(Y[:1], Y[1:2])
my_rho2 = np.corrcoef(Y[:1], Y[2:3]) 
my_rho3 = np.corrcoef(Y[:1], Y[3:4]) 
print(Y)
print(my_rho1)
print(my_rho2)
print(my_rho3)



[[91 77]
 [41 32]
 [30 25]
 [88 76]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

Дано матрицю. Знайти ранг матриці:

In [69]:
from numpy.linalg import matrix_rank

a = np.array([[ 1,  4,2],
              [7, 3, 4],
              [9, 16, 7]])

matrix_rank(a)

3

Знайти визначник матриці:

In [6]:
import numpy as np  # Находим определитель матрицы



a = np.array([[ 1,  4,2],
              [7, 3, 4],
              [9, 16, 7]])

Z = np.linalg.det(a)

Z



75.00000000000004

Знайти власні значення та власні вектори матриці: 

In [7]:
import numpy as np  # Находим определитель матрицы



a = np.array([[ 1,  4,2],
              [7, 3, 4],
              [9, 16, 7]])

S = np.linalg.eig(a)

S

(array([16.17181791, -1.15439661, -4.0174213 ]),
 array([[-0.22043126, -0.36215706,  0.20413127],
        [-0.38880481, -0.25344255, -0.63049022],
        [-0.89456184,  0.89700008,  0.74887416]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [5]:
import numpy as np # Число, котрое чаще всего встречается в массиве

a = np.random.randint(0,10,50)

d = np.argmax(np.bincount(a))

print(a)
d

[1 6 5 9 5 6 2 1 3 3 8 0 1 4 1 7 6 9 7 6 0 3 7 7 8 0 3 0 8 9 0 2 5 3 3 2 1
 5 4 3 7 3 1 0 6 6 0 7 9 2]


3

Виведіть лише парні числа, що діляться на 5:

In [19]:
import numpy as np

a = np.random.randint(0,20,50)

for x in np.nditer(a):
   if x%2 == 0 and x%5 == 0: 
       print(x)

print(a)

0
10
0
10
[ 4  3 14 12  4  2  3 18  7  8  7  0  6 14  9 12  3 13  4 16 18  6 17  7
  3 10  3  1  7  5  5 13  0  1 10  1 16 18 19 16  6  7 17 12  8  8  8  9
 16  7]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [4]:
import numpy as np # Решение системы линейных уравнений
from numpy import linalg as la

a = [[2,   5],
     [1, -10]]

b = [1, 3]

x = la.solve(a,b)

x
#np.dot(a,x)